config/routes.rb
Rails.application.routes.draw do
   get '/orders/upload'
#  get 'welcome/index'
  #resources :articles
  root 'welcome#index'
  resources :orders do
	get 'update'
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
require "net/http"
require "uri"
require "json"

class OrdersController < ApplicationController
  def index
    @orders = Order.all
    @totalprice = Order.sum(:total_price)
    @totaltax = Order.sum(:total_tax)
  end
  def show
    @order = Order.find(params[:id])
  end
  def new
  end
  def create
	#Condition to check if the order is to be added
	if (params[:add_order] == "1")
	 @order = Order.new(order_params)
  	 @order.save
	end
	#Condition to check if orders are to be uploaded from Shopify URL
	if (params[:shopify_upload] == "1")
		1.upto(3) do |number|	
			uri = URI.parse("https://shopicruit.myshopify.com/admin/orders.json?page=#{number}&access_token=c32313df0d0ef512ca64d5b336a0d7c6")
			response = Net::HTTP.get_response(uri)
			data = JSON.parse(response.body)
			data['orders'].each { |item|
				order = Order.new(:orderid => item['id'],:total_price => item['total_price'],:total_tax => item['total_tax'],:item_name =>'N/A')
				order.save
			}
		end
	end
	#Condition to check if database is to be truncated
	if (params[:delete_entries] == "1")
		Order.delete_all
	end	
    	@orders = Order.all
    	@totalprice = Order.sum(:total_price)
    	@totaltax = Order.sum(:total_tax)
	render action: "index"
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  private
  def order_params
    params.require(:order).permit(:orderid, :total_price,:total_tax,:item_name)
  end
end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  def index
  end
  def calculate
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
</style>
</head>
<body>

<center><h1>Orders Summary</h1></center>
 
<%= link_to 'New order/Upload from Shopify URL', new_order_path %>

<h2>Total Price: <%= @totalprice%> </h2>
<h2>Total Tax: <%= @totaltax %> </h2>

<table>
  <tr>
    <th>Order Id</th>
    <th>Item Name</th>
    <th>Total Price</th>
    <th>Total Tax</th>
  </tr>
 
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.orderid%></td>
      <td><%= order.item_name%></td>
      <td><%= order.total_price%></td>
      <td><%= order.total_tax%></td>
      <td><%= link_to 'Show', order_path(order) %></td>
      <td><%= link_to 'Destroy', order_path(order),
              method: :delete,
              data: { confirm: 'Are you sure you want to delete this entry?' } %></td>
    </tr>
  <% end %>
</table>
</body>
</html>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= form_for :order, url: orders_path do |f| %>
<p>
    <%= f.label :order_id%><br>
    <%= f.text_field :orderid %>
  </p>
 
  <p>
    <%= f.label :total_price %><br>
    <%= f.text_area :total_price %>
  </p>
 
  <p>
    <%= f.label :total_tax %><br>
    <%= f.text_area :total_tax %>
  </p>

  <p>
    <%= f.label :item_name %><br>
    <%= f.text_area :item_name%>
  </p>
  <p>
   <%= check_box_tag(:shopify_upload) %>
        <%= label_tag(:shopify_upload, "Upload the data from Shopify URL?  (https://shopicruit.myshopify.com/admin/orders.json)") %>
  </p>
  <p>
   <%= check_box_tag(:add_order) %>
	<%= label_tag(:add_order, "Add the above order?") %>
  </p>
  <p>
  <%= check_box_tag(:delete_entries) %>
	<%= label_tag(:delete_entries, "Truncate Database") %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p>
  <strong>Order ID:</strong>
  <%= @order.orderid %>
</p>
 
<p>
  <strong>Item Name:</strong>
  <%= @order.item_name%>
</p>
<p>
  <strong>Total Price:</strong>
  <%= @order.total_price %>
</p>
<p>
  <strong>Total Tax:</strong>
  <%= @order.total_tax%>
</p>
<%= link_to 'Back', orders_path %>

app/views/orders/upload.html.erb
<h1>Listing orders</h1>
 
<table>
  <tr>
    <th>Order Id</th>
    <th>Item Name</th>
    <th>Total Price</th>
    <th>Total Tax</th>
  </tr>
 
  <% @orders.each do |order| %>
    <tr>
      <td><%= order.orderid%></td>
      <td><%= order.item_name%></td>
      <td><%= order.total_price%></td>
      <td><%= order.total_tax%></td>
      <td><%= link_to 'Show', order_path(order) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New article', new_order_path %>
<%= link_to "Upload",:action=>"update", :controller=>"orders"%>

app/views/upload/index.html.erb
<h1>Upload#index</h1>
<%=form_for :upload, url: url_for( :controller => :upload, :action => :calculate) do |f| %>
<%=form_for :upload, url: url_for( :controller => :upload, :action => :calculate) do |f| %>
    <div class="field">
      <%= f.label :link %><br />
      <%= f.text_field :link %>
    </div> 

  <div class="actions">
    <%= f.submit %>
<% end %>

app/views/welcome/index.html.erb
<center><h1>Shopify Application</h1></center>
<img src="shopify-logo.png" alt="Shopify Logo" height="100" width="200">
<%= link_to 'Order Management', controller: 'orders' %>